/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e5e1e3",
        "inverse-primary": "#e4bccc",
        "surface-container": "#f1edef",
        "surface-variant": "#e5e1e3",
        "surface-tint": "#755564",
        "tertiary-fixed": "#e9ddff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#4e4448",
        "primary-fixed": "#ffd8e8",
        "on-surface": "#1c1b1d",
        "tertiary-fixed-dim": "#cdc1e4",
        "primary-container": "#fad0e1",
        "on-secondary-fixed-variant": "#194c5e",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#d2c3c7",
        "surface-container-low": "#f6f2f4",
        "inverse-on-surface": "#f3f0f2",
        "surface-bright": "#fcf8fa",
        "secondary": "#356477",
        "primary-fixed-dim": "#e4bccc",
        "on-primary-container": "#775765",
        "on-secondary-container": "#39697b",
        "tertiary": "#635a78",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#2c1420",
        "on-tertiary-fixed": "#1f1731",
        "on-background": "#1c1b1d",
        "secondary-container": "#b7e7fd",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#4b425f",
        "tertiary-container": "#e2d5f9",
        "outline": "#807478",
        "primary": "#755564",
        "on-tertiary-container": "#645b79",
        "surface-container-high": "#ebe7e9",
        "secondary-fixed": "#bbe9ff",
        "background": "#fcf8fa",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#5c3e4c",
        "surface": "#fcf8fa",
        "on-secondary-fixed": "#001f29",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#9ecde3",
        "on-error": "#ffffff",
        "surface-dim": "#dcd9db",
        "inverse-surface": "#313032"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "24px",
        "section-gap": "48px",
        "base": "8px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-lg": ["'TH Sarabun PSK'", "Sarabun", "sans-serif"],
        "body-md": ["'TH Sarabun PSK'", "Sarabun", "sans-serif"],
        "headline-md": ["'TH Sarabun PSK'", "Sarabun", "sans-serif"],
        "label-md": ["'TH Sarabun PSK'", "Sarabun", "sans-serif"],
        "label-sm": ["'TH Sarabun PSK'", "Sarabun", "sans-serif"],
        "body-lg": ["'TH Sarabun PSK'", "Sarabun", "sans-serif"],
        "headline-lg-mobile": ["'TH Sarabun PSK'", "Sarabun", "sans-serif"],
        "headline-xl": ["'TH Sarabun PSK'", "Sarabun", "sans-serif"],
        // Fallback for general usage
        "sans": ["'TH Sarabun PSK'", "Sarabun", "ui-sans-serif", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-md": ["22px", { "lineHeight": "30px", "fontWeight": "400" }],
        "headline-md": ["36px", { "lineHeight": "42px", "fontWeight": "700" }],
        "label-md": ["20px", { "lineHeight": "28px", "letterSpacing": "0.01em", "fontWeight": "700" }],
        "label-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["26px", { "lineHeight": "34px", "fontWeight": "400" }],
        "headline-lg-mobile": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-xl": ["52px", { "lineHeight": "60px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
